version: '3.8'

services:
  wikimetron-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8200:8000"
    environment:
      - DATABASE_URL=postgresql://wiki_user:wiki_pass@postgres:5432/wikimetron_db
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
    command: uvicorn wikimetron.api.main:app --host 0.0.0.0 --port 8000 --reload

  wikimetron-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8300:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8200
      - REACT_APP_VERSION=1.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=wikimetron_db
      - POSTGRES_USER=wiki_user  
      - POSTGRES_PASSWORD=wiki_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "55432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
